# Generated by Django 5.2.6 on 2025-10-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core_productoslacteos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidodetalle',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoDetalle',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
