# Generated by Django 5.2.6 on 2025-11-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_core_productoslacteos', '0002_remove_producto_categoria_remove_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_personalizado',
        ),
    ]
